serviceAccount: projects/project-2-458822/serviceAccounts/hemanth-861@project-2-458822.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/image:latest', '.']
  dir: 'project-3-dr/project-3-dr/my_app'

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/image:latest']

# Step 3: Deploy to Cloud Run in primary region (e.g., us-central1)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run', 'deploy', 'my-app-primary',
      '--image', 'gcr.io/$PROJECT_ID/image:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--vpc-us-central1'
    ]

# Step 4: Deploy to Cloud Run in secondary region (e.g., us-east1)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run', 'deploy', 'my-app-secondary',
      '--image', 'gcr.io/$PROJECT_ID/image:latest',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--vpc-us-east1'
    ]

# Step 5: Terraform Init
- name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd project-3-dr/project-3-dr
      terraform init

# Step 6: Terraform Apply
- name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd project-3-dr/project-3-dr
      terraform apply -auto-approve

images:
- 'gcr.io/$PROJECT_ID/image:latest'
