serviceAccount: projects/project-2-458822/serviceAccounts/hemanth-861@project-2-458822.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
steps:
# 1. Build the Docker image from my_app folder
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/image:latest', '.']
  dir: 'my_app'

# 2. Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/image:latest']

# 3. Terraform Init inside my_app folder
- name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd my_app
      terraform init

# 4. Terraform Apply inside my_app folder
- name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd my_app
      terraform apply -auto-approve

images:
- 'gcr.io/$PROJECT_ID/image:latest'
